fork = false
frame = "full"
size = [1024, 924]
idle = true
maximized = false
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
mouse-cursor-icon = "arrow" # i-beam
title-hidden = true
vsync = false
wsl = false

[font]
normal = ["JetBrainsMono Nerd Font"]
size = 11

[box-drawing]
mode = "selected-native"
selected = " î‚¹  ğŸ®‘ğŸ®’ î¸€î¸î¸‚ î¸ƒî¸„î¸…â–•â–â–â– â–„â– â–Œâ–ˆ"

